### ISSUE TITLE
Error when Starting

### ISSUE THREAD

**Issue by Andr705** [WiPi-Hunter/PiKarma#2]
hello my dear,
using kali and installed as perinstructions
but when starting got below:

sh: 1: iwconfig: not found
Traceback (most recent call last):
  File "PiKarma.py", line 153, in <module>
    sniff_channel_hop(iface)
  File "PiKarma.py", line 59, in sniff_channel_hop
    sniff(iface=iface, count=4, prn=air_scan)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 570, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 459, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 1] Operation not permitted

even start with sudo no matter
any suggestions pls.

p.s. seems Python version require 3.0 ?

**Comment by besimaltnok** [comment]
Hi, 

which system do you use?
I guess the **iwconfig** command does not work.

**Comment by Andr705** [comment]
Hello , same thinking on first look but start commend in terminal working fine.
I'm using Kali Linux last addition on Lenovo X-220 and trying on HP Pavilion 6820
but unfo same result.

only ideas as using shell Cinamon with NOT-root user
but trying to start yrs programm at ROOT terminal not help.

tkx for help & ideas

**Comment by besimaltnok** [comment]
Hi,

Can you send to me output of "iwconfig" as normally? for wireless interface

**Comment by Andr705** [comment]
sudo iwconfig
wwan0     no wireless extensions.

wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=15 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
eth0      no wireless extensions.

lo        no wireless extensions.

wlan1     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=30 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

**Comment by Andr705** [comment]
sudo airmon-ng

PHY	Interface	Driver		Chipset

phy0	wlan0		iwlwifi		Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)
phy1	wlan1		rt2800usb	Ralink Technology, Corp. RT2870/RT3070

**Comment by Andr705** [comment]
hope it will help to find solution
tkx vm in advance

**Comment by wald1972** [comment]
Using usb realtek 88xxau Rasp. 3b Debian Bullseye, same issue on kali Linux 

admin@rasp:~/PiKarma $ python PiKarma.py -h
  File "/home/admin/PiKarma/PiKarma.py", line 92
    print colored("\033[1m[*] KARMA Attack activity detected.", 'magenta', attrs=['reverse', 'blink'])
          ^
SyntaxError: invalid syntax
